# Generated by Django 5.0.1 on 2024-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.TextField(max_length=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(blank=True, null=True, upload_to='mainView/static/mainView/img')),
            ],
            options={
                'verbose_name': 'Main',
                'verbose_name_plural': 'Mains',
            },
        ),
        migrations.CreateModel(
            name='Articles1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.TextField(max_length=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('name', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(blank=True, null=True, upload_to='mainView/static/mainView/img')),
            ],
            options={
                'verbose_name': 'Buy',
                'verbose_name_plural': 'Buys',
            },
        ),
    ]
