# Generated by Django 5.0.1 on 2024-02-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles1',
            name='name',
        ),
    ]
